config/routes.rb
Rails.application.routes.draw do
  # route to: 'posts#index'

  resources :posts do
    resources :comments
  end
end

app/models/comment.rb
class Comment <ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post <ActiveRecord::Base
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController <ApplicationController

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Post.comments.create!(comment_params)
    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to comments_path
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to posts_commments_path
  end

  private
  def comment_params
    params.require(:comment).permit(:title)
  end


end

app/controllers/posts_controller.rb
class PostsController <ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create!(post_params)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scribble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<h2>Posts</h2>
<h3><%= link_to "New Post", new_post_path %></h3>
<ul>
  <% @posts.each do |post| %>
    <li>
      <p>
        <%= link_to post.title, post %> | <%= link_to 'Delete', post_path(post),
                                                method: :delete,
                                                data: { confirm: 'Are you sure?' } %>
        
      </p>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1> Hi! </h1>

<h2>Edit Post</h2>

<%= render 'form' %>